//  PreparerChecklistService.swift
//  FLO - Finance Ledger Optimizer
//
//  Version 1.0 — CPA-facing "what your preparer needs" checklist
//  Copyright © 2026 Finch & Poppy Co LLC. All rights reserved.
//
//  Generates a comprehensive checklist of documents and information
//  a tax preparer needs based on the user's entities, filing status,
//  and transaction history. Designed for sharing with a CPA.
//

import Foundation
import SwiftData

// MARK: - Result Types

struct PreparerChecklist: Identifiable {
    let id = UUID()
    let taxYear: Int
    let generatedDate: Date
    let filingStatus: String
    let sections: [PreparerSection]
    let entitySummaries: [EntityPreparerSummary]

    var totalItems: Int { sections.reduce(0) { $0 + $1.items.count } }
}

struct PreparerSection: Identifiable {
    let id = UUID()
    let title: String
    let icon: String
    let items: [PreparerItem]
    let notes: String?
}

struct PreparerItem: Identifiable {
    let id = UUID()
    let label: String
    let detail: String?
    let isProvided: Bool
    let source: String? // e.g., "FLO Tax Handoff PDF", "Bank statement"
}

struct EntityPreparerSummary: Identifiable {
    let id = UUID()
    let businessName: String
    let businessType: String
    let ein: String?
    let naicsCode: String?
    let formRequired: String
    let hasPartners: Bool
    let partnerCount: Int
    let hasAssets: Bool
    let assetCount: Int
    let hasCarryforwards: Bool
    let carryforwardCount: Int
}

// MARK: - Service

@MainActor
final class PreparerChecklistService {
    static let shared = PreparerChecklistService()

    private init() {}

    // MARK: - Public API

    func generateChecklist(
        businesses: [BusinessProfile],
        transactions: [Transaction],
        taxSettings: TaxSettings?,
        taxYear: Int
    ) -> PreparerChecklist {
        let settings = taxSettings ?? TaxSettings()
        var sections: [PreparerSection] = []

        // Section 1: Personal Information
        sections.append(personalInfoSection(settings: settings))

        // Section 2: Income Documents
        sections.append(incomeDocumentsSection(transactions: transactions, taxYear: taxYear))

        // Section 3: Business Records (per entity)
        for business in businesses where business.isActive {
            sections.append(businessRecordsSection(business: business, transactions: transactions, taxYear: taxYear))
        }

        // Section 4: Deductions & Credits
        sections.append(deductionsSection(settings: settings, transactions: transactions, taxYear: taxYear))

        // Section 5: Estimated Tax Payments
        sections.append(estimatedPaymentsSection(settings: settings, taxYear: taxYear))

        // Section 6: Prior Year Info
        sections.append(priorYearSection(settings: settings))

        // Entity summaries
        let entitySummaries = businesses
            .filter { $0.isActive }
            .map { entitySummary(for: $0) }

        return PreparerChecklist(
            taxYear: taxYear,
            generatedDate: Date(),
            filingStatus: settings.filingStatus.displayName,
            sections: sections,
            entitySummaries: entitySummaries
        )
    }

    /// Generates a shareable text version of the checklist.
    func generateShareableText(checklist: PreparerChecklist) -> String {
        var lines: [String] = []

        lines.append("TAX PREPARATION CHECKLIST — \(checklist.taxYear)")
        lines.append("Generated by FLO on \(DateFormatter.mediumDate.string(from: checklist.generatedDate))")
        lines.append("Filing Status: \(checklist.filingStatus)")
        lines.append(String(repeating: "=", count: 50))
        lines.append("")

        // Entity overview
        if !checklist.entitySummaries.isEmpty {
            lines.append("BUSINESS ENTITIES")
            lines.append(String(repeating: "-", count: 30))
            for entity in checklist.entitySummaries {
                lines.append("\(entity.businessName) (\(entity.businessType))")
                if let ein = entity.ein { lines.append("  EIN: \(ein)") }
                if let naics = entity.naicsCode { lines.append("  NAICS: \(naics)") }
                lines.append("  Form: \(entity.formRequired)")
                if entity.hasPartners { lines.append("  Partners: \(entity.partnerCount)") }
                if entity.hasAssets { lines.append("  Depreciable Assets: \(entity.assetCount)") }
                if entity.hasCarryforwards { lines.append("  Carryforwards: \(entity.carryforwardCount)") }
                lines.append("")
            }
        }

        // Sections
        for section in checklist.sections {
            lines.append(section.title.uppercased())
            lines.append(String(repeating: "-", count: 30))
            for item in section.items {
                let check = item.isProvided ? "[x]" : "[ ]"
                var line = "\(check) \(item.label)"
                if let detail = item.detail { line += " — \(detail)" }
                if let source = item.source { line += " (Source: \(source))" }
                lines.append(line)
            }
            if let notes = section.notes {
                lines.append("  Note: \(notes)")
            }
            lines.append("")
        }

        lines.append(String(repeating: "=", count: 50))
        lines.append("Generated by FLO — Finance Ledger Optimizer")
        lines.append("This is not tax advice. Consult a qualified tax professional.")

        return lines.joined(separator: "\n")
    }

    // MARK: - Section Builders

    private func personalInfoSection(settings: TaxSettings) -> PreparerSection {
        PreparerSection(
            title: "Personal Information",
            icon: "person.text.rectangle",
            items: [
                PreparerItem(label: "Filing Status", detail: settings.filingStatus.displayName, isProvided: true, source: "FLO Settings"),
                PreparerItem(label: "Social Security Number(s)", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Date(s) of Birth", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Current Address", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Bank Account (for direct deposit)", detail: "Routing + account number", isProvided: false, source: nil),
                PreparerItem(label: "Dependent Information", detail: "Names, SSNs, dates of birth", isProvided: false, source: nil),
            ],
            notes: "Bring government-issued ID for identity verification if first-time client."
        )
    }

    private func incomeDocumentsSection(transactions: [Transaction], taxYear: Int) -> PreparerSection {
        let calendar = Calendar.current
        let yearTxns = transactions.filter { calendar.component(.year, from: $0.date) == taxYear }
        let hasW2Income = yearTxns.contains { $0.isIncome && $0.financeType == .personal }
        let hasSEIncome = yearTxns.contains { $0.isIncome && $0.financeType == .business }

        var items: [PreparerItem] = []

        if hasW2Income {
            items.append(PreparerItem(label: "W-2 Forms", detail: "From all employers", isProvided: false, source: nil))
        }

        items.append(contentsOf: [
            PreparerItem(label: "1099-NEC / 1099-MISC", detail: "Freelance and contract income", isProvided: false, source: nil),
            PreparerItem(label: "1099-INT / 1099-DIV", detail: "Interest and dividend income", isProvided: false, source: nil),
            PreparerItem(label: "1099-B", detail: "Stock/investment sales", isProvided: false, source: nil),
            PreparerItem(label: "1099-R", detail: "Retirement distributions", isProvided: false, source: nil),
            PreparerItem(label: "1099-G", detail: "Government payments (unemployment, state refund)", isProvided: false, source: nil),
            PreparerItem(label: "K-1 Forms Received", detail: "From partnerships, S-corps, trusts", isProvided: false, source: nil),
        ])

        if hasSEIncome {
            items.append(PreparerItem(
                label: "Self-Employment Income Summary",
                detail: "Gross receipts by entity",
                isProvided: true,
                source: "FLO Tax Handoff PDF"
            ))
        }

        return PreparerSection(
            title: "Income Documents",
            icon: "doc.text.fill",
            items: items,
            notes: nil
        )
    }

    private func businessRecordsSection(business: BusinessProfile, transactions: [Transaction], taxYear: Int) -> PreparerSection {
        let calendar = Calendar.current
        let bizTxns = transactions.filter {
            calendar.component(.year, from: $0.date) == taxYear
            && $0.financeType == .business
            && !$0.isTransfer
        }
        let hasExpenses = bizTxns.contains { !$0.isIncome && !$0.isTransfer }
        let hasAssets = !(business.assets?.isEmpty ?? true)
        let hasPartners = business.isPartnership

        var items: [PreparerItem] = [
            PreparerItem(
                label: "Income & Expense Summary",
                detail: "\(bizTxns.count) transactions",
                isProvided: true,
                source: "FLO Tax Handoff PDF"
            ),
        ]

        if let ein = business.taxId, !ein.isEmpty {
            items.append(PreparerItem(label: "EIN", detail: ein, isProvided: true, source: "FLO"))
        } else {
            items.append(PreparerItem(label: "EIN", detail: "Not on file", isProvided: false, source: nil))
        }

        if hasExpenses {
            items.append(PreparerItem(
                label: "Expense Categorization",
                detail: "Mapped to IRS form lines",
                isProvided: true,
                source: "FLO Tax Handoff PDF"
            ))
        }

        if hasAssets {
            let assetCount = business.assets?.count ?? 0
            items.append(PreparerItem(
                label: "Depreciation Schedule",
                detail: "\(assetCount) asset(s) with MACRS tables",
                isProvided: true,
                source: "FLO Tax Handoff PDF"
            ))
        }

        items.append(PreparerItem(label: "Vehicle/Mileage Log", detail: "If business use claimed", isProvided: false, source: nil))
        items.append(PreparerItem(label: "Home Office Measurements", detail: "Square footage if applicable", isProvided: false, source: nil))

        if hasPartners {
            let partnerCount = business.sortedPartners.count
            items.append(PreparerItem(
                label: "Partner Capital Accounts",
                detail: "\(partnerCount) partner(s)",
                isProvided: true,
                source: "FLO Tax Handoff PDF"
            ))
            items.append(PreparerItem(label: "Operating Agreement", detail: "Current version", isProvided: false, source: nil))
        }

        items.append(PreparerItem(label: "Bank Statements", detail: "All business accounts, Jan–Dec", isProvided: false, source: nil))
        items.append(PreparerItem(label: "Receipt Documentation", detail: "For expenses over $75", isProvided: false, source: nil))

        return PreparerSection(
            title: business.businessName,
            icon: "building.2.fill",
            items: items,
            notes: "Form: \(formForBusinessType(business.businessType))"
        )
    }

    private func deductionsSection(settings: TaxSettings, transactions: [Transaction], taxYear: Int) -> PreparerSection {
        PreparerSection(
            title: "Deductions & Credits",
            icon: "text.badge.minus",
            items: [
                PreparerItem(label: "Mortgage Interest (1098)", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Property Tax Statements", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "State/Local Taxes Paid", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Charitable Contributions", detail: "Cash and non-cash receipts", isProvided: false, source: nil),
                PreparerItem(label: "Medical Expenses", detail: "If itemizing", isProvided: false, source: nil),
                PreparerItem(label: "Student Loan Interest (1098-E)", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Tuition Payments (1098-T)", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "Child/Dependent Care Expenses", detail: "Provider name, EIN, amounts", isProvided: false, source: nil),
                PreparerItem(label: "Health Insurance Premiums", detail: "1095-A if Marketplace", isProvided: false, source: nil),
                PreparerItem(label: "HSA Contributions (5498-SA)", detail: nil, isProvided: false, source: nil),
                PreparerItem(label: "IRA/401k Contributions", detail: "Traditional and Roth", isProvided: false, source: nil),
            ],
            notes: nil
        )
    }

    private func estimatedPaymentsSection(settings: TaxSettings, taxYear: Int) -> PreparerSection {
        PreparerSection(
            title: "Estimated Tax Payments",
            icon: "calendar.badge.clock",
            items: [
                PreparerItem(label: "Federal Estimated Payments", detail: "Dates and amounts for all 4 quarters", isProvided: false, source: nil),
                PreparerItem(label: "State Estimated Payments", detail: "Dates and amounts", isProvided: false, source: nil),
                PreparerItem(label: "Prior Year Overpayment Applied", detail: "Amount applied to \(taxYear) from \(taxYear - 1)", isProvided: false, source: nil),
            ],
            notes: "Include confirmation numbers or canceled checks for verification."
        )
    }

    private func priorYearSection(settings: TaxSettings) -> PreparerSection {
        let hasPriorLiability = (settings.priorYearTaxLiability ?? 0) > 0

        return PreparerSection(
            title: "Prior Year Reference",
            icon: "clock.arrow.circlepath",
            items: [
                PreparerItem(
                    label: "Prior Year Tax Return",
                    detail: "Full copy of last year's return",
                    isProvided: false,
                    source: nil
                ),
                PreparerItem(
                    label: "Prior Year Tax Liability",
                    detail: hasPriorLiability
                        ? NumberFormatter.appCurrency.string(from: NSNumber(value: settings.priorYearTaxLiability ?? 0))
                        : "Not on file",
                    isProvided: hasPriorLiability,
                    source: hasPriorLiability ? "FLO Settings" : nil
                ),
                PreparerItem(label: "Prior Year AGI", detail: "Needed for e-file identity verification", isProvided: false, source: nil),
            ],
            notes: "If switching preparers, provide prior year return for carryforward review."
        )
    }

    // MARK: - Entity Summary

    private func entitySummary(for business: BusinessProfile) -> EntityPreparerSummary {
        EntityPreparerSummary(
            businessName: business.businessName,
            businessType: business.businessType.displayName,
            ein: business.taxId,
            naicsCode: business.naicsCode,
            formRequired: formForBusinessType(business.businessType),
            hasPartners: business.isPartnership,
            partnerCount: business.sortedPartners.count,
            hasAssets: !(business.assets?.isEmpty ?? true),
            assetCount: business.assets?.count ?? 0,
            hasCarryforwards: !(business.carryforwards?.isEmpty ?? true),
            carryforwardCount: business.carryforwards?.filter { $0.status == .active || $0.status == .partiallyUtilized }.count ?? 0
        )
    }

    private func formForBusinessType(_ type: BusinessType) -> String {
        switch type {
        case .soleProprietorship, .llc: return "Schedule C (Form 1040)"
        case .partnership: return "Form 1065 + K-1s"
        case .farm: return "Schedule F (Form 1040) or Form 1065"
        case .rentalProperty: return "Schedule E (Form 1040)"
        default: return "Consult preparer"
        }
    }
}
